### ISSUE TITLE
您好我想问一下 是不可以增加票数啊

### ISSUE THREAD

**Issue by kyo77** [BBDrive/damai_ticket#2]

**Comment by BBDrive** [comment]
可以增加票数，当时要看购票须知里面一张订单最多可以买几张票哦

**Comment by kyo77** [comment]
好的，谢谢您，我上午跑了一下，输出台一直显示  没有弹出实名者弹窗

BBDrive <notifications@github.com>于2019年9月24日 周二下午3:59写道：

**Comment by BBDrive** [comment]
你有观察到浏览器是什么情况吗？

**Comment by kyo77** [comment]
浏览器就是卡在提交订单那块，然后点不了确认提交订单那个按钮

BBDrive <notifications@github.com>于2019年9月24日 周二下午4:04写道：

**Comment by kyo77** [comment]
我敢肯定您的代码肯定没问题   估计是我设置的时候有问题

BBDrive <notifications@github.com>于2019年9月24日 周二下午4:04写道：

**Comment by BBDrive** [comment]
这个我在前几天抢周杰伦的票的时候也出现过，点击了提交订单但是没有反应，一直卡在那个页面，我觉得可能是抢票人数过多，因为在抢人气一般的都没有问题。

**Comment by kyo77** [comment]
嗯嗯对   明天周董的又要开票了  可以在试试  如果要是还出错  我及时给您反馈信息

BBDrive <notifications@github.com>于2019年9月24日 周二下午4:14写道：

**Comment by BBDrive** [comment]
好，感谢！之前抢华晨宇的票（大概80w+人）抢成功过，但是周董的抢了2次了都抢不到，我也会根据反馈优化代码的

**Comment by kyo77** [comment]
好嘞   如果您方便的话 可以留您一个QQ号吗 然后我加您 这样就方便一些

BBDrive <notifications@github.com>于2019年9月24日 周二下午4:21写道：

**Comment by BBDrive** [comment]
QQ 842089432
