### ISSUE TITLE
命令行下中文乱码

### ISSUE THREAD

**Issue by phantomedc** [BBDrive/damai_ticket#3]
建议print的时候，
```python
print(u"抢票成功".encode('gbk'))
```

**Comment by BBDrive** [comment]
好的，谢谢您的反馈，之前忘记考虑到windows命令行的编码方式了





------------------ 原始邮件 ------------------
发件人: Shuo <notifications@github.com&gt;
发送时间: 2019年9月25日 11:11
收件人: BBDrive/damai_ticket <damai_ticket@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[BBDrive/damai_ticket] 命令行下中文乱码 (#3)




建议print的时候，
 print(u"抢票成功".encode('gbk'))
